---
# Renovate Types
- name: renovate/github-action
  color: "0aa002"
- name: renovate/docker
  color: "0052CC"
- name: renovate/jdk-version
  color: "b0722f"
- name: renovate/gradle-version
  color: "006B75"
- name: renovate/gradle-package
  color: "812df6"

# Semantic Types
- name: type/digest
  color: "53b4e5"
- name: type/patch
  color: "0e8a16"
- name: type/minor
  color: "d9640b"
- name: type/major
  color: "f62d2d"
