---
# Areas
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/build
  color: "D93F0B"

# Renovate Types
- name: renovate/github-action
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/java-version
  color: "B60205"
- name: renovate/docker
  color: "0052CC"
- name: renovate/gradle
  color: "006B75"

# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"