---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Image Versions
description: Takes a version string and returns a valid semantic version if possible

inputs:
  input-version:
    description: Input Version
    required: true

outputs:
  valid-release:
    description: If version is valid semantic versioning
    value: ${{ steps.version.outputs.valid-release }}
  semantic:
    description: Semantic Version
    value: ${{ steps.version.outputs.semantic }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22.x

    - name: Install Semver
      shell: bash
      run: npm install semver

    - name: Determine Image Versions
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      id: version
      with:
        script: |
          const semver = require('semver');

          const inputVersion = '${{ inputs.input-version }}';
          const parsedSemver = semver.coerce(inputVersion, { includePrerelease: true });
          const isValidSemver = parsedSemver !== null;
          core.setOutput('valid-release', isValidSemver);
          core.setOutput('semantic', parsedSemver?.version);
