---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Image Versions
description: Takes a version string and returns a valid semantic version if possible

inputs:
  input-version:
    description: Input Version
    required: true

outputs:
  valid-release:
    description: If version is valid semantic versioning
    value: ${{ steps.version.outputs.valid-release }}
  semantic:
    description: Semantic Version
    value: ${{ steps.version.outputs.semantic }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: 22.x

    - name: Install Semver
      shell: bash
      run: npm install semver

    - name: Determine Image Versions
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: version
      with:
        script: |
          const semver = require('semver');

          const inputVersion = '${{ inputs.input-version }}';
          const parsedSemver = semver.coerce(inputVersion, { includePrerelease: true });
          const isValidSemver = parsedSemver !== null;
          core.setOutput('valid-release', isValidSemver);
          core.setOutput('semantic', parsedSemver?.version);
