x-podman:
  in_pod: false

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/java:21-bookworm
    container_name: workspace
    env_file: devcontainer.env
    volumes:
      - ..:/workspace:cached
    ports:
      - 8080:8080
    command: sleep infinity
    user: vscode
    userns_mode: keep-id:uid=1000,gid=1000
