---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Bake Options
description: Returns various fields from the docker-bake.hcl file

outputs:
  platforms:
    description: Platforms
    value: ${{ steps.bake.outputs.platforms }}

runs:
  using: composite
  steps:
    - name: Bake Options
      id: bake
      shell: bash
      run: |
          BAKE_OPTS=$(docker buildx bake --file ./docker-bake.hcl image-all --print 2>/dev/null)

          PLATFORMS=$(jq --raw-output --compact-output '.target."image-all".platforms' <<< "$BAKE_OPTS")
          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
