on:
  push:
    branches:
      - 'main'
env:
  REGISTRY: ghcr.io

jobs:
  build-push-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to Github Packages
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set current date as env variable
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/kobot
          tags: |
            type=raw,value=latest
            type=raw,value=RELEASE.${{ env.date }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.12.0
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
