on:
  push:
    branches:
      - 'main'

jobs:
  build-push-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set current date as env variable
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/opentoucan/kotbot:RELEASE.${{ env.date }},ghcr.io/opentoucan/kotbot:latest