on: push
#    branches:
#      - 'main'
#  workflow_run:
#    workflows: [test]
#    types: [completed]

jobs:
  build-push-docker:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set current date as env variable
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/opentoucan/kotbot:RELEASE.${{ env.date }},ghcr.io/opentoucan/kotbot:latest