on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["17"]
        java-distribution: ["corretto"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: test with Gradle Wrapper
      run: ./gradlew --no-daemon check --info     